<<<<<<< HEAD
MONGODB_HOST: mongodb-{{ env }}.daws86s.fun # mongodb-dev.daws86s.fun
REDIS_HOST: redis-{{ env }}.daws86s.fun
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.daws86s.fun
CART_HOST: cart.backend-alb-{{ env }}.daws86s.fun
USER_HOST: user.backend-alb-{{ env }}.daws86s.fun
RABBITMQ_HOST: rabbitmq-{{ env }}.daws86s.fun
MYSQL_HOST: mysql-{{ env }}.daws86s.fun
SHIPPING_HOST: shipping.backend-alb-{{ env }}.daws86s.fun
PAYMENT_HOST: payment.backend-alb-{{ env }}.daws86s.fun
=======
MONGODB_HOST: mongodb.surekhadevops.biz
REDIS_HOST: redis.surekhadevops.biz
CATALOGUE_HOST: catalogue.surekhadevops.biz
CART_HOST: cart.surekhadevops.biz
USER_HOST: user.surekhadevops.biz
SHIPPING_HOST: shipping.surekhadevops.biz
PAYMENT_HOST: payment.surekhadevops.biz
MYSQL_HOST: mysql.surekhadevops.biz
RABBITMQ_HOST: rabbitmq.surekhadevops.biz
FRONTEND_HOST: frontend.surekhadevops.biz
>>>>>>> f083818b4add734bcc3977b2abd360034cb412f6
