<<<<<<< HEAD
- name: app setup
=======
- name: app setup 
>>>>>>> f083818b4add734bcc3977b2abd360034cb412f6
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml

<<<<<<< HEAD
# changed this as part of latest python3-devel from repos have upgraded openssl-libs but other openssl packages are old in AMI, so mismatch occured. we are upgrading before installing python or after
- name: upgrade openssl packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
  - openssl
  - openssl-libs
  - openssh
  - openssh-server
  - openssh-clients

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml

- name: system setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
=======
- name: NodeJs setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python.yaml 

- name: System setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system_setup.yaml
>>>>>>> f083818b4add734bcc3977b2abd360034cb412f6
