<<<<<<< HEAD
- name: create roboshop system user
  ansible.builtin.user:
    name: roboshop
    comment: RoboShop System user
    system: true
    shell: /sbin/nologin
    home: /app
# Safe to remove directory, because 2nd time if we run it will download freshly. no error if does not exist
=======
- name: add roboshop system user
  ansible.builtin.user:
    name: roboshop
    comment: system user roboshop
    shell: /sbin/nologin
    home: /app

# Safe to remove directory, because 2nd time if we run it will download freshly. no error if doesn't exit
>>>>>>> f083818b4add734bcc3977b2abd360034cb412f6
- name: remove app directory
  ansible.builtin.file:
    path: /app
    state: absent

<<<<<<< HEAD
- name: create app directory
  ansible.builtin.file:
    state: directory
    path: /app
=======
- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory   
>>>>>>> f083818b4add734bcc3977b2abd360034cb412f6

- name: Delete {{ component }} file
  ansible.builtin.file:
    path: /tmp/{{ component }}.zip
    state: absent

<<<<<<< HEAD
- name: download {{ component }} application
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip

- name: extract {{ component }} application
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app
=======
- name: Download {{ component }} file
  ansible.builtin.get_url:
    url: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3.zip
    dest: /tmp/{{ component }}.zip 

- name: Extract {{ component }} file
  ansible.builtin.unarchive:
    src: /tmp/{{ component }}.zip
    dest: /app  
>>>>>>> f083818b4add734bcc3977b2abd360034cb412f6
    remote_src: yes