<<<<<<< HEAD
- name: install python package
=======
- name: Install python package
>>>>>>> f083818b4add734bcc3977b2abd360034cb412f6
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - python3
  - gcc
  - python3-devel

- name: install dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9
  args:
    chdir: /app